service: serverless-test
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-2
  timeout: 900
  environment:
    ALLOWS_INSECURE_SSL_CERTIFICATES: true


plugins:
  - serverless-plugin-typescript
  - serverless-offline


functions:
  weatherApi:
    handler: src/handlers/weather.handler
    events:
      - httpApi:
          path: /
          method: post

